apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: z6etk8ify-python
  janus-idp.io/tekton: z6etk8ify-python
  backstage.io/kubernetes-id: z6etk8ify-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: z6etk8ify-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
